//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chidrenContainer : DbContext
    {
        public chidrenContainer()
            : base("name=chidrenContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<用户> 用户Set { get; set; }
        public virtual DbSet<管理员> 管理员Set { get; set; }
        public virtual DbSet<广告轮播> 广告轮播Set { get; set; }
        public virtual DbSet<喜欢记录> 喜欢记录Set { get; set; }
        public virtual DbSet<报名记录> 报名记录Set { get; set; }
        public virtual DbSet<精选活动> 精选活动Set { get; set; }
        public virtual DbSet<活动> 活动Set { get; set; }
        public virtual DbSet<关注> 关注Set { get; set; }
        public virtual DbSet<活动评论> 活动评论Set { get; set; }
        public virtual DbSet<意见反馈> 意见反馈Set { get; set; }
        public virtual DbSet<相册> 相册Set { get; set; }
        public virtual DbSet<动态> 动态Set { get; set; }
        public virtual DbSet<动态附件> 动态附件Set { get; set; }
        public virtual DbSet<动态点赞记录> 动态点赞记录Set { get; set; }
        public virtual DbSet<动态评论> 动态评论Set { get; set; }
        public virtual DbSet<主题> 主题Set { get; set; }
    }
}
