//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 主题
    {
        public 主题()
        {
            this.活动 = new HashSet<活动>();
        }
    
        public int Id { get; set; }
        public string 名称 { get; set; }
        public string 图片 { get; set; }
    
        public virtual ICollection<活动> 活动 { get; set; }
    }
}
