//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 动态
    {
        public 动态()
        {
            this.动态附件 = new HashSet<动态附件>();
            this.动态点赞记录 = new HashSet<动态点赞记录>();
            this.动态评论 = new HashSet<动态评论>();
        }
    
        public int Id { get; set; }
        public string 内容 { get; set; }
        public System.DateTime 发布时间 { get; set; }
        public int 点赞数 { get; set; }
        public Nullable<bool> delete { get; set; }
        public int 用户Id { get; set; }
    
        public virtual ICollection<动态附件> 动态附件 { get; set; }
        public virtual 用户 用户 { get; set; }
        public virtual ICollection<动态点赞记录> 动态点赞记录 { get; set; }
        public virtual ICollection<动态评论> 动态评论 { get; set; }
    }
}
