//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 广告轮播
    {
        public int Id { get; set; }
        public string 图片 { get; set; }
        public long 活动编号 { get; set; }
        public string 广告链接 { get; set; }
        public string 广告标题 { get; set; }
        public string 广告信息 { get; set; }
        public string 类别 { get; set; }
    }
}
