//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 活动
    {
        public 活动()
        {
            this.delete = false;
            this.精选活动 = new HashSet<精选活动>();
            this.喜欢记录 = new HashSet<喜欢记录>();
            this.活动评论 = new HashSet<活动评论>();
            this.报名记录 = new HashSet<报名记录>();
        }
    
        public int Id { get; set; }
        public string 标题 { get; set; }
        public string 内容 { get; set; }
        public string 主题图片 { get; set; }
        public string 活动地址 { get; set; }
        public System.DateTime 开始时间 { get; set; }
        public System.DateTime 结束时间 { get; set; }
        public System.DateTime 报名截止时间 { get; set; }
        public long 阅读人数 { get; set; }
        public long 喜欢人数 { get; set; }
        public long 报名人数 { get; set; }
        public Nullable<bool> delete { get; set; }
        public int 用户Id { get; set; }
        public Nullable<System.DateTime> 发起时间 { get; set; }
        public int 主题Id { get; set; }
    
        public virtual 用户 用户 { get; set; }
        public virtual ICollection<精选活动> 精选活动 { get; set; }
        public virtual ICollection<喜欢记录> 喜欢记录 { get; set; }
        public virtual ICollection<活动评论> 活动评论 { get; set; }
        public virtual ICollection<报名记录> 报名记录 { get; set; }
        public virtual 主题 主题 { get; set; }
    }
}
