//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 用户
    {
        public 用户()
        {
            this.喜欢记录 = new HashSet<喜欢记录>();
            this.报名记录 = new HashSet<报名记录>();
            this.好友 = new HashSet<关注>();
            this.活动 = new HashSet<活动>();
            this.活动评论 = new HashSet<活动评论>();
            this.相册 = new HashSet<相册>();
            this.动态 = new HashSet<动态>();
            this.动态点赞记录 = new HashSet<动态点赞记录>();
            this.意见反馈 = new HashSet<意见反馈>();
            this.动态评论 = new HashSet<动态评论>();
        }
    
        public int Id { get; set; }
        public string 昵称 { get; set; }
        public string 密码 { get; set; }
        public string 手机号 { get; set; }
        public string 头像 { get; set; }
        public string 类别 { get; set; }
        public System.DateTime 生日 { get; set; }
        public string 地址 { get; set; }
        public Nullable<bool> delete { get; set; }
        public string 性别 { get; set; }
        public string 个性签名 { get; set; }
    
        public virtual ICollection<喜欢记录> 喜欢记录 { get; set; }
        public virtual ICollection<报名记录> 报名记录 { get; set; }
        public virtual ICollection<关注> 好友 { get; set; }
        public virtual ICollection<活动> 活动 { get; set; }
        public virtual ICollection<活动评论> 活动评论 { get; set; }
        public virtual ICollection<相册> 相册 { get; set; }
        public virtual ICollection<动态> 动态 { get; set; }
        public virtual ICollection<动态点赞记录> 动态点赞记录 { get; set; }
        public virtual ICollection<意见反馈> 意见反馈 { get; set; }
        public virtual ICollection<动态评论> 动态评论 { get; set; }
    }
}
