//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 管理员
    {
        public int Id { get; set; }
        public string 登录名 { get; set; }
        public string 姓名 { get; set; }
        public string 管理类型 { get; set; }
        public long 管理等级 { get; set; }
    }
}
