//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class 精选活动
    {
        public int Id { get; set; }
        public long 价格 { get; set; }
        public int 活动Id { get; set; }
    
        public virtual 活动 活动 { get; set; }
    }
}
